### PR TITLE
Testing improvements

### PR DESCRIPTION
**Pull request by tas50**
Run integration tests directly in Travis

### CODE REVIEW

**Comment by tas50** [comment]
@cwjohnston @luckymike PRs not building for some odd reason

**Comment by cwjohnston** [comment]
@tas50 I'm at a loss here. This PR isn't present in Travis at all, and, unlike a webhook integration, I don't see a way to re-fire a notification to the Travis CI "service" in the repo settings.

**Comment by tas50** [comment]
@cwjohnston odd. I'll look around tomorrow and see if there's some magical fix for this

**Comment by tas50** [comment]
Turns out I was blocking builds off develop. Oops

**Pull request closed without merging**
